export const spotifyResponses = {
  playlists: {
    href: 'https://api.spotify.com/v1/users/wizzler/playlists',
    items: [
      {
        collaborative: false,
        external_urls: {
          spotify:
            'http://open.spotify.com/user/wizzler/playlists/53Y8wT46QIMz5H4WQ8O22c',
        },
        href:
          'https://api.spotify.com/v1/users/wizzler/playlists/53Y8wT46QIMz5H4WQ8O22c',
        id: '53Y8wT46QIMz5H4WQ8O22c',
        images: [],
        name: 'Wizzlers Big Playlist',
        owner: {
          external_urls: {
            spotify: 'http://open.spotify.com/user/wizzler',
          },
          href: 'https://api.spotify.com/v1/users/wizzler',
          id: 'wizzler',
          type: 'user',
          uri: 'spotify:user:wizzler',
        },
        public: true,
        snapshot_id:
          'bNLWdmhh+HDsbHzhckXeDC0uyKyg4FjPI/KEsKjAE526usnz2LxwgyBoMShVL+z+',
        tracks: {
          href:
            'https://api.spotify.com/v1/users/wizzler/playlists/53Y8wT46QIMz5H4WQ8O22c/tracks',
          total: 30,
        },
        type: 'playlist',
        uri: 'spotify:user:wizzler:playlist:53Y8wT46QIMz5H4WQ8O22c',
      },
      {
        collaborative: false,
        external_urls: {
          spotify:
            'http://open.spotify.com/user/wizzlersmate/playlists/1AVZz0mBuGbCEoNRQdYQju',
        },
        href:
          'https://api.spotify.com/v1/users/wizzlersmate/playlists/1AVZz0mBuGbCEoNRQdYQju',
        id: '1AVZz0mBuGbCEoNRQdYQju',
        images: [],
        name: 'Another Playlist',
        owner: {
          external_urls: {
            spotify: 'http://open.spotify.com/user/wizzlersmate',
          },
          href: 'https://api.spotify.com/v1/users/wizzlersmate',
          id: 'wizzlersmate',
          type: 'user',
          uri: 'spotify:user:wizzlersmate',
        },
        public: true,
        snapshot_id:
          'Y0qg/IT5T02DKpw4uQKc/9RUrqQJ07hbTKyEeDRPOo9LU0g0icBrIXwVkHfQZ/aD',
        tracks: {
          href:
            'https://api.spotify.com/v1/users/wizzlersmate/playlists/1AVZz0mBuGbCEoNRQdYQju/tracks',
          total: 58,
        },
        type: 'playlist',
        uri: 'spotify:user:wizzlersmate:playlist:1AVZz0mBuGbCEoNRQdYQju',
      },
    ],
    limit: 9,
    next: null,
    offset: 0,
    previous: null,
    total: 9,
  },
  playlist: {
    collaborative: false,
    description: 'Having friends over for dinner? Here´s the perfect playlist.',
    external_urls: {
      spotify:
        'http://open.spotify.com/user/spotify/playlist/59ZbFPES4DQwEjBpWHzrtC',
    },
    followers: {
      href: null,
      total: 143350,
    },
    href:
      'https://api.spotify.com/v1/users/spotify/playlists/59ZbFPES4DQwEjBpWHzrtC',
    id: '59ZbFPES4DQwEjBpWHzrtC',
    images: [
      {
        url: 'https://i.scdn.co/image/68b6a65573a55095e9c0c0c33a274b18e0422736',
      },
    ],
    name: 'Dinner with Friends',
    owner: {
      external_urls: {
        spotify: 'http://open.spotify.com/user/spotify',
      },
      href: 'https://api.spotify.com/v1/users/spotify',
      id: 'spotify',
      type: 'user',
      uri: 'spotify:user:spotify',
    },
    public: null,
    snapshot_id:
      'bNLWdmhh+HDsbHzhckXeDC0uyKyg4FjPI/KEsKjAE526usnz2LxwgyBoMShVL+z+',
    tracks: {
      href:
        'https://api.spotify.com/v1/users/spotify/playlists/59ZbFPES4DQwEjBpWHzrtC/tracks',
      items: [
        {
          added_at: '2014-09-01T04:21:28Z',
          added_by: {
            external_urls: {
              spotify: 'http://open.spotify.com/user/spotify',
            },
            href: 'https://api.spotify.com/v1/users/spotify',
            id: 'spotify',
            type: 'user',
            uri: 'spotify:user:spotify',
          },
          is_local: false,
          track: {
            album: {
              album_type: 'single',
              available_markets: [
                'AD',
                'AR',
                'AT',
                'AU',
                'BE',
                'BG',
                'BO',
                'BR',
                'CH',
                'CL',
                'CO',
                'CR',
                'CY',
                'CZ',
                'DK',
                'DO',
                'EC',
                'EE',
                'ES',
                'FI',
                'FR',
                'GB',
                'GR',
                'GT',
                'HK',
                'HN',
                'HU',
                'IE',
                'IS',
                'IT',
                'LI',
                'LT',
                'LU',
                'LV',
                'MC',
                'MT',
                'MY',
                'NI',
                'NL',
                'NO',
                'NZ',
                'PA',
                'PE',
                'PH',
                'PL',
                'PT',
                'PY',
                'RO',
                'SE',
                'SG',
                'SI',
                'SK',
                'SV',
                'TR',
                'TW',
                'UY',
              ],
              external_urls: {
                spotify:
                  'https://open.spotify.com/album/5GWoXPsTQylMuaZ84PC563',
              },
              href: 'https://api.spotify.com/v1/albums/5GWoXPsTQylMuaZ84PC563',
              id: '5GWoXPsTQylMuaZ84PC563',
              images: [
                {
                  height: 640,
                  url:
                    'https://i.scdn.co/image/47421900e7534789603de84c03a40a826c058e45',
                  width: 640,
                },
                {
                  height: 300,
                  url:
                    'https://i.scdn.co/image/0d447b6faae870f890dc5780cc58d9afdbc36a1d',
                  width: 300,
                },
                {
                  height: 64,
                  url:
                    'https://i.scdn.co/image/d926b3e5f435ef3ac0874b1ff1571cf675b3ef3b',
                  width: 64,
                },
              ],
              name: "I''m Not The Only One",
              type: 'album',
              uri: 'spotify:album:5GWoXPsTQylMuaZ84PC563',
            },
            artists: [
              {
                external_urls: {
                  spotify:
                    'https://open.spotify.com/artist/2wY79sveU1sp5g7SokKOiI',
                },
                href:
                  'https://api.spotify.com/v1/artists/2wY79sveU1sp5g7SokKOiI',
                id: '2wY79sveU1sp5g7SokKOiI',
                name: 'Sam Smith',
                type: 'artist',
                uri: 'spotify:artist:2wY79sveU1sp5g7SokKOiI',
              },
            ],
            available_markets: [
              'AD',
              'AR',
              'AT',
              'AU',
              'BE',
              'BG',
              'BO',
              'BR',
              'CH',
              'CL',
              'CO',
              'CR',
              'CY',
              'CZ',
              'DK',
              'DO',
              'EC',
              'EE',
              'ES',
              'FI',
              'FR',
              'GB',
              'GR',
              'GT',
              'HK',
              'HN',
              'HU',
              'IE',
              'IS',
              'IT',
              'LI',
              'LT',
              'LU',
              'LV',
              'MC',
              'MT',
              'MY',
              'NI',
              'NL',
              'NO',
              'NZ',
              'PA',
              'PE',
              'PH',
              'PL',
              'PT',
              'PY',
              'RO',
              'SE',
              'SG',
              'SI',
              'SK',
              'SV',
              'TR',
              'TW',
              'UY',
            ],
            disc_number: 1,
            duration_ms: 204732,
            explicit: false,
            external_ids: {
              isrc: 'GBUM71403920',
            },
            external_urls: {
              spotify: 'https://open.spotify.com/track/4i9sYtSIlR80bxje5B3rUb',
            },
            href: 'https://api.spotify.com/v1/tracks/4i9sYtSIlR80bxje5B3rUb',
            id: '4i9sYtSIlR80bxje5B3rUb',
            name: "I''m Not The Only One - Radio Edit",
            popularity: 45,
            preview_url:
              'https://p.scdn.co/mp3-preview/dd64cca26c69e93ea78f1fff2cc4889396bb6d2f',
            track_number: 1,
            type: 'track',
            uri: 'spotify:track:4i9sYtSIlR80bxje5B3rUb',
          },
        },
      ],
      limit: 100,
      next:
        'https://api.spotify.com/v1/users/spotify/playlists/59ZbFPES4DQwEjBpWHzrtC/tracks?offset=100&limit=100',
      offset: 0,
      previous: null,
      total: 105,
    },
    type: 'playlist',
    uri: 'spotify:user:spotify:playlist:59ZbFPES4DQwEjBpWHzrtC',
  },
  favorites: {
    href: 'https://api.spotify.com/v1/me/tracks?offset=0&limit=20',
    items: [
      {
        added_at: '2016-10-24T15:03:07Z',
        track: {
          album: {
            album_type: 'album',
            artists: [
              {
                external_urls: {
                  spotify:
                    'https://open.spotify.com/artist/0LIll5i3kwo5A3IDpipgkS',
                },
                href:
                  'https://api.spotify.com/v1/artists/0LIll5i3kwo5A3IDpipgkS',
                id: '0LIll5i3kwo5A3IDpipgkS',
                name: 'Squirrel Nut Zippers',
                type: 'artist',
                uri: 'spotify:artist:0LIll5i3kwo5A3IDpipgkS',
              },
            ],
            available_markets: [
              'AD',
              'AR',
              'AT',
              'AU',
              'BE',
              'BG',
              'BO',
              'BR',
              'CH',
              'CL',
              'CO',
              'CR',
              'CY',
              'CZ',
              'DE',
              'DK',
              'DO',
              'EC',
              'EE',
              'ES',
              'FI',
              'FR',
              'GB',
              'GR',
              'GT',
              'HK',
              'HN',
              'HU',
              'ID',
              'IE',
              'IS',
              'IT',
              'JP',
              'LI',
              'LT',
              'LU',
              'LV',
              'MC',
              'MT',
              'MY',
              'NI',
              'NL',
              'NO',
              'NZ',
              'PA',
              'PE',
              'PH',
              'PL',
              'PT',
              'PY',
              'SE',
              'SG',
              'SK',
              'SV',
              'TR',
              'TW',
              'UY',
            ],
            external_urls: {
              spotify: 'https://open.spotify.com/album/63GBbuUNBel2ovJjUrfh5r',
            },
            href: 'https://api.spotify.com/v1/albums/63GBbuUNBel2ovJjUrfh5r',
            id: '63GBbuUNBel2ovJjUrfh5r',
            images: [
              {
                height: 640,
                url:
                  'https://i.scdn.co/image/e9c5fd63935b08ed27a7a5b0e65b2c6bf600fc4a',
                width: 640,
              },
              {
                height: 300,
                url:
                  'https://i.scdn.co/image/416b6589d9e2d91147ff5072d640d0041b04cb41',
                width: 300,
              },
              {
                height: 64,
                url:
                  'https://i.scdn.co/image/4bb6b451b8edde5881a5fcbe1a54bc8538f407ec',
                width: 64,
              },
            ],
            name: 'The Best of Squirrel Nut Zippers',
            type: 'album',
            uri: 'spotify:album:63GBbuUNBel2ovJjUrfh5r',
          },
          artists: [
            {
              external_urls: {
                spotify:
                  'https://open.spotify.com/artist/0LIll5i3kwo5A3IDpipgkS',
              },
              href: 'https://api.spotify.com/v1/artists/0LIll5i3kwo5A3IDpipgkS',
              id: '0LIll5i3kwo5A3IDpipgkS',
              name: 'Squirrel Nut Zippers',
              type: 'artist',
              uri: 'spotify:artist:0LIll5i3kwo5A3IDpipgkS',
            },
          ],
          available_markets: [
            'AD',
            'AR',
            'AT',
            'AU',
            'BE',
            'BG',
            'BO',
            'BR',
            'CH',
            'CL',
            'CO',
            'CR',
            'CY',
            'CZ',
            'DE',
            'DK',
            'DO',
            'EC',
            'EE',
            'ES',
            'FI',
            'FR',
            'GB',
            'GR',
            'GT',
            'HK',
            'HN',
            'HU',
            'ID',
            'IE',
            'IS',
            'IT',
            'JP',
            'LI',
            'LT',
            'LU',
            'LV',
            'MC',
            'MT',
            'MY',
            'NI',
            'NL',
            'NO',
            'NZ',
            'PA',
            'PE',
            'PH',
            'PL',
            'PT',
            'PY',
            'SE',
            'SG',
            'SK',
            'SV',
            'TR',
            'TW',
            'UY',
          ],
          disc_number: 1,
          duration_ms: 137040,
          explicit: false,
          external_ids: {
            isrc: 'USMA20215185',
          },
          external_urls: {
            spotify: 'https://open.spotify.com/track/2jpDioAB9tlYXMdXDK3BGl',
          },
          href: 'https://api.spotify.com/v1/tracks/2jpDioAB9tlYXMdXDK3BGl',
          id: '2jpDioAB9tlYXMdXDK3BGl',
          name: 'Good Enough For Granddad',
          popularity: 19,
          preview_url:
            'https://p.scdn.co/mp3-preview/32cc6f7a3fca362dfcde753f0339f42539f15c9a',
          track_number: 1,
          type: 'track',
          uri: 'spotify:track:2jpDioAB9tlYXMdXDK3BGl',
        },
      },
    ],
    limit: 20,
    next: 'https://api.spotify.com/v1/me/tracks?offset=20&limit=20',
    offset: 0,
    previous: null,
    total: 53,
  },
  checkFavorite: [true],
  user: {
    country: 'SE',
    display_name: 'JM Wizzler',
    email: 'email@example.com',
    external_urls: {
      spotify: 'https://open.spotify.com/user/wizzler',
    },
    followers: {
      href: null,
      total: 3829,
    },
    href: 'https://api.spotify.com/v1/users/wizzler',
    id: 'wizzler',
    images: [
      {
        height: null,
        url:
          'https://fbcdn-profile-a.akamaihd.net/hprofile-ak-frc3/t1.0-1/1970403_10152215092574354_1798272330_n.jpg',
        width: null,
      },
    ],
    product: 'premium',
    type: 'user',
    uri: 'spotify:user:wizzler',
  },
  top50: {
    description:
      'Tu actualización diaria de las canciones más escuchadas ahora mismo en Global.',
    spotifyWeb: 'https://open.spotify.com/playlist/37i9dQZEVXbMDoHDwVN2tF',
    id: '37i9dQZEVXbMDoHDwVN2tF',
    imageUrl:
      'https://charts-images.scdn.co/assets/locale_en/regional/daily/region_global_large.jpg',
    name: 'Top 50: Global',
    songsTotal: 50,
    tracks: [
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'Justice',
        artists: ['Justin Bieber', 'Daniel Caesar', 'Giveon'],
        duration: '3: 18',
        id: '4iJyoBOLtHqaGxP12qzhQI',
        name: 'Peaches',
        spotifyWeb: 'https://open.spotify.com/track/4iJyoBOLtHqaGxP12qzhQI',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'drivers license',
        artists: ['Olivia Rodrigo'],
        duration: '4: 02',
        id: '7lPN2DXiMsVn7XUKtOW1CS',
        name: 'drivers license',
        spotifyWeb: 'https://open.spotify.com/track/7lPN2DXiMsVn7XUKtOW1CS',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'Justice',
        artists: ['Justin Bieber'],
        duration: '2: 51',
        id: '1nahzW3kfMuwReTka28tH5',
        name: 'Hold On',
        spotifyWeb: 'https://open.spotify.com/track/1nahzW3kfMuwReTka28tH5',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'Astronaut In The Ocean',
        artists: ['Masked Wolf'],
        duration: '2: 13',
        id: '3VT8hOC5vuDXBsHrR53WFh',
        name: 'Astronaut In The Ocean',
        spotifyWeb: 'https://open.spotify.com/track/3VT8hOC5vuDXBsHrR53WFh',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'Sin Miedo (del Amor y Otros Demonios) ∞',
        artists: ['Kali Uchis'],
        duration: '2: 40',
        id: '6tDDoYIxWvMLTdKpjFkc1B',
        name: 'telepatía',
        spotifyWeb: 'https://open.spotify.com/track/6tDDoYIxWvMLTdKpjFkc1B',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'After Hours',
        artists: ['The Weeknd'],
        duration: '3: 36',
        id: '5QO79kh1waicV47BqGRL3g',
        name: 'Save Your Tears',
        spotifyWeb: 'https://open.spotify.com/track/5QO79kh1waicV47BqGRL3g',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'Leave The Door Open',
        artists: ['Bruno Mars', 'Anderson .Paak', 'Silk Sonic'],
        duration: '4: 02',
        id: '7MAibcTli4IisCtbHKrGMh',
        name: 'Leave The Door Open',
        spotifyWeb: 'https://open.spotify.com/track/7MAibcTli4IisCtbHKrGMh',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'Justice',
        artists: ['Justin Bieber', 'Khalid'],
        duration: '2: 54',
        id: '6F2r4HgpJnvKDmkN6JEN6J',
        name: 'As I Am',
        spotifyWeb: 'https://open.spotify.com/track/6F2r4HgpJnvKDmkN6JEN6J',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'After Hours',
        artists: ['The Weeknd'],
        duration: '3: 20',
        id: '0VjIjW4GlUZAMYd2vXMi3b',
        name: 'Blinding Lights',
        spotifyWeb: 'https://open.spotify.com/track/0VjIjW4GlUZAMYd2vXMi3b',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'TAKE TIME',
        artists: ['Giveon'],
        duration: '3: 18',
        id: '3FAJ6O0NOHQV8Mc5Ri6ENp',
        name: 'Heartbreak Anniversary',
        spotifyWeb: 'https://open.spotify.com/track/3FAJ6O0NOHQV8Mc5Ri6ENp',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'EL ÚLTIMO TOUR DEL MUNDO',
        artists: ['Bad Bunny', 'Jhay Cortez'],
        duration: '3: 25',
        id: '4MzXwWMhyBbmu6hOcLVD49',
        name: 'DÁKITI',
        spotifyWeb: 'https://open.spotify.com/track/4MzXwWMhyBbmu6hOcLVD49',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'The Business',
        artists: ['Tiësto'],
        duration: '2: 44',
        id: '6f3Slt0GbA2bPZlz0aIFXN',
        name: 'The Business',
        spotifyWeb: 'https://open.spotify.com/track/6f3Slt0GbA2bPZlz0aIFXN',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'Justice',
        artists: ['Justin Bieber'],
        duration: '3: 11',
        id: '2WnAKZefdRHxtBEkRjFOHC',
        name: 'Anyone',
        spotifyWeb: 'https://open.spotify.com/track/2WnAKZefdRHxtBEkRjFOHC',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'Future Nostalgia',
        artists: ['Dua Lipa', 'DaBaby'],
        duration: '3: 23',
        id: '5nujrmhLynf4yMoMtj8AQF',
        name: 'Levitating (feat. DaBaby)',
        spotifyWeb: 'https://open.spotify.com/track/5nujrmhLynf4yMoMtj8AQF',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'Up (Instrumental)',
        artists: ['Cardi B'],
        duration: '2: 37',
        id: '1M4OcYkxAtu3ErzSgDEfoi',
        name: 'Up',
        spotifyWeb: 'https://open.spotify.com/track/1M4OcYkxAtu3ErzSgDEfoi',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'Calling My Phone',
        artists: ['Lil Tjay', '6LACK'],
        duration: '3: 25',
        id: '5Kskr9LcNYa0tpt5f0ZEJx',
        name: 'Calling My Phone',
        spotifyWeb: 'https://open.spotify.com/track/5Kskr9LcNYa0tpt5f0ZEJx',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'Hot Pink',
        artists: ['Doja Cat'],
        duration: '3: 47',
        id: '60ynsPSSKe6O3sfwRnIBRf',
        name: 'Streets',
        spotifyWeb: 'https://open.spotify.com/track/60ynsPSSKe6O3sfwRnIBRf',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'F*CK LOVE (SAVAGE)',
        artists: ['The Kid LAROI'],
        duration: '2: 41',
        id: '27OeeYzk6klgBh83TSvGMA',
        name: 'WITHOUT YOU',
        spotifyWeb: 'https://open.spotify.com/track/27OeeYzk6klgBh83TSvGMA',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'Mood (feat. iann dior)',
        artists: ['24kGoldn', 'iann dior'],
        duration: '2: 21',
        id: '3tjFYV6RSFtuktYl3ZtYcq',
        name: 'Mood (feat. iann dior)',
        spotifyWeb: 'https://open.spotify.com/track/3tjFYV6RSFtuktYl3ZtYcq',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'Justice',
        artists: ['Justin Bieber', 'Chance the Rapper'],
        duration: '3: 32',
        id: '6Xgq7MvZiet0hVi3KaDSgJ',
        name: 'Holy',
        spotifyWeb: 'https://open.spotify.com/track/6Xgq7MvZiet0hVi3KaDSgJ',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'Bandido',
        artists: ['Myke Towers', 'Juhn'],
        duration: '3: 53',
        id: '1xK1Gg9SxG8fy2Ya373oqb',
        name: 'Bandido',
        spotifyWeb: 'https://open.spotify.com/track/1xK1Gg9SxG8fy2Ya373oqb',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'R',
        artists: ['ROSÉ'],
        duration: '2: 48',
        id: '2pn8dNVSpYnAtlKFC8Q0DJ',
        name: 'On The Ground',
        spotifyWeb: 'https://open.spotify.com/track/2pn8dNVSpYnAtlKFC8Q0DJ',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'Scary Hours 2',
        artists: ['Drake'],
        duration: '2: 58',
        id: '3aQem4jVGdhtg116TmJnHz',
        name: 'What’s Next',
        spotifyWeb: 'https://open.spotify.com/track/3aQem4jVGdhtg116TmJnHz',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'Justice',
        artists: ['Justin Bieber', 'benny blanco'],
        duration: '2: 29',
        id: '3S8jK1mGzQi24ilFb45DAZ',
        name: 'Lonely',
        spotifyWeb: 'https://open.spotify.com/track/3S8jK1mGzQi24ilFb45DAZ',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'Ella No Es Tuya (Remix)',
        artists: ['Rochy RD', 'Myke Towers', 'Nicki Nicole'],
        duration: '3: 38',
        id: '5YYW3yRktprLRr47WK219Y',
        name: 'Ella No Es Tuya - Remix',
        spotifyWeb: 'https://open.spotify.com/track/5YYW3yRktprLRr47WK219Y',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'Friday (feat. Mufasa & Hypeman) [Dopamine Re-Edit]',
        artists: ['Riton', 'Nightcrawlers', 'Mufasa & Hypeman', 'Dopamine'],
        duration: '2: 49',
        id: '4cG7HUWYHBV6R6tHn1gxrl',
        name: 'Friday (feat. Mufasa & Hypeman) - Dopamine Re-Edit',
        spotifyWeb: 'https://open.spotify.com/track/4cG7HUWYHBV6R6tHn1gxrl',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'EL ÚLTIMO TOUR DEL MUNDO',
        artists: ['Bad Bunny', 'ROSALÍA'],
        duration: '3: 23',
        id: '2XIc1pqjXV3Cr2BQUGNBck',
        name: 'LA NOCHE DE ANOCHE',
        spotifyWeb: 'https://open.spotify.com/track/2XIc1pqjXV3Cr2BQUGNBck',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'Future Nostalgia (The Moonlight Edition)',
        artists: ['Dua Lipa'],
        duration: '2: 46',
        id: '1diS6nkxMQc3wwC4G1j0bh',
        name: "We're Good",
        spotifyWeb: 'https://open.spotify.com/track/1diS6nkxMQc3wwC4G1j0bh',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'BE',
        artists: ['BTS'],
        duration: '3: 19',
        id: '4saklk6nie3yiGePpBwUoc',
        name: 'Dynamite',
        spotifyWeb: 'https://open.spotify.com/track/4saklk6nie3yiGePpBwUoc',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'Justice',
        artists: ['Justin Bieber', 'The Kid LAROI'],
        duration: '2: 38',
        id: '137mSruegm1u6x9NvwiagR',
        name: 'Unstable',
        spotifyWeb: 'https://open.spotify.com/track/137mSruegm1u6x9NvwiagR',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'Small Town Boy (Track By Track)',
        artists: ['Duncan Laurence'],
        duration: '3: 05',
        id: '1J14CdDAvBTE1AJYUOwl6C',
        name: 'Arcade',
        spotifyWeb: 'https://open.spotify.com/track/1J14CdDAvBTE1AJYUOwl6C',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'Fine Line',
        artists: ['Harry Styles'],
        duration: '2: 54',
        id: '6UelLqGlWMcVH1E5c4H7lY',
        name: 'Watermelon Sugar',
        spotifyWeb: 'https://open.spotify.com/track/6UelLqGlWMcVH1E5c4H7lY',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'Good Days',
        artists: ['SZA'],
        duration: '4: 39',
        id: '3YJJjQPAbDT7mGpX3WtQ9A',
        name: 'Good Days',
        spotifyWeb: 'https://open.spotify.com/track/3YJJjQPAbDT7mGpX3WtQ9A',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'Revelación - EP',
        artists: ['Selena Gomez', 'Rauw Alejandro'],
        duration: '3: 06',
        id: '079Ey5uxL04AKPQgVQwx5h',
        name: 'Baila Conmigo (with Rauw Alejandro)',
        spotifyWeb: 'https://open.spotify.com/track/079Ey5uxL04AKPQgVQwx5h',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'Positions',
        artists: ['Ariana Grande'],
        duration: '2: 52',
        id: '35mvY5S1H3J2QZyna3TFe0',
        name: 'positions',
        spotifyWeb: 'https://open.spotify.com/track/35mvY5S1H3J2QZyna3TFe0',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'Justice',
        artists: ['Justin Bieber'],
        duration: '2: 36',
        id: '3T03rPwlL8NVk1yIaxeD8U',
        name: 'Off My Face',
        spotifyWeb: 'https://open.spotify.com/track/3T03rPwlL8NVk1yIaxeD8U',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'Wellerman (Sea Shanty / 220 KID x Billen Ted Remix)',
        artists: ['Nathan Evans', '220 KID', 'Billen Ted'],
        duration: '1: 57',
        id: '3iw6V4LH7yPj1ESORX9RIN',
        name: 'Wellerman - Sea Shanty / 220 KID x Billen Ted Remix',
        spotifyWeb: 'https://open.spotify.com/track/3iw6V4LH7yPj1ESORX9RIN',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'Divinely Uninspired To A Hellish Extent',
        artists: ['Lewis Capaldi'],
        duration: '3: 02',
        id: '7qEHsqek33rTcFNT9PFqLf',
        name: 'Someone You Loved',
        spotifyWeb: 'https://open.spotify.com/track/7qEHsqek33rTcFNT9PFqLf',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'Justice',
        artists: ['Justin Bieber'],
        duration: '2: 33',
        id: '6I3mqTwhRpn34SLVafSH7G',
        name: 'Ghost',
        spotifyWeb: 'https://open.spotify.com/track/6I3mqTwhRpn34SLVafSH7G',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'Loyalty Over Royalty',
        artists: ['CJ'],
        duration: '2: 03',
        id: '1t9WgS8FN0534tLBRwbaxO',
        name: 'Whoopty',
        spotifyWeb: 'https://open.spotify.com/track/1t9WgS8FN0534tLBRwbaxO',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'BICHOTA',
        artists: ['KAROL G'],
        duration: '2: 59',
        id: '7vrJn5hDSXRmdXoR30KgF1',
        name: 'BICHOTA',
        spotifyWeb: 'https://open.spotify.com/track/7vrJn5hDSXRmdXoR30KgF1',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'Your Love (9PM)',
        artists: ['ATB', 'Topic', 'A7S'],
        duration: '2: 30',
        id: '5YaskwnGDZFDRipaqzbwQx',
        name: 'Your Love (9PM)',
        spotifyWeb: 'https://open.spotify.com/track/5YaskwnGDZFDRipaqzbwQx',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'Los Legendarios 001',
        artists: ['Los Legendarios', 'Wisin', 'Jhay Cortez'],
        duration: '4: 22',
        id: '7Bk0uXKk1uPT0XuQbpFzvs',
        name: 'Fiel',
        spotifyWeb: 'https://open.spotify.com/track/7Bk0uXKk1uPT0XuQbpFzvs',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'Future Nostalgia',
        artists: ['Dua Lipa'],
        duration: '3: 03',
        id: '3PfIrDoz19wz7qK7tYeu62',
        name: "Don't Start Now",
        spotifyWeb: 'https://open.spotify.com/track/3PfIrDoz19wz7qK7tYeu62',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'Dreamland (+ Bonus Levels)',
        artists: ['Glass Animals'],
        duration: '3: 59',
        id: '02MWAaffLxlfxAUY7c5dvx',
        name: 'Heat Waves',
        spotifyWeb: 'https://open.spotify.com/track/02MWAaffLxlfxAUY7c5dvx',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'Goosebumps (Remix)',
        artists: ['Travis Scott', 'HVME'],
        duration: '2: 43',
        id: '5uEYRdEIh9Bo4fpjDd4Na9',
        name: 'Goosebumps - Remix',
        spotifyWeb: 'https://open.spotify.com/track/5uEYRdEIh9Bo4fpjDd4Na9',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'Justice',
        artists: ['Justin Bieber'],
        duration: '2: 33',
        id: '0oaY19dUwZimIgzn3ZZLZO',
        name: '2 Much',
        spotifyWeb: 'https://open.spotify.com/track/0oaY19dUwZimIgzn3ZZLZO',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: '911',
        artists: ['Sech'],
        duration: '3: 36',
        id: '2TksvaRivgAEj780DgRB73',
        name: '911',
        spotifyWeb: 'https://open.spotify.com/track/2TksvaRivgAEj780DgRB73',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'Justice',
        artists: ['Justin Bieber'],
        duration: '3: 07',
        id: '5NU40QTlXrDUJzDBdv79bg',
        name: 'Deserve You',
        spotifyWeb: 'https://open.spotify.com/track/5NU40QTlXrDUJzDBdv79bg',
      },
      {
        addedAt: '2021-03-23T11:17:38.000Z',
        album: 'Más Negro Que Rojo',
        artists: ['Boza'],
        duration: '3: 06',
        id: '3VvA1wSxukMLsvXoXtlwWx',
        name: "Hecha Pa' Mi",
        spotifyWeb: 'https://open.spotify.com/track/3VvA1wSxukMLsvXoXtlwWx',
      },
    ],
  },
};
